version: "3.9"

services:
  neo4j:
    container_name: 'neo4j_container'
    image         : 'neo4j_container'
    build:
      context     : ./dockerfile
      dockerfile  : neo4jfile
    volumes:
      - ./config:/var/lib/neo4j/conf:rw
      - ./init_network:/var/lib/neo4j/init_network:rw
      - ./networks:/var/lib/neo4j/import:rw
      - ./query_execution:/scripts:rw